wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1662953553.288801
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.1
      8:
      - 5
      10:
      - 1
batchsize:
  desc: null
  value: 64
cols:
  desc: null
  value:
  - 주차
  - 내부CO2
  - 내부습도
  - 내부온도
  - 지온
  - 강우감지
  - 일사량
  - 지습
  - 급액횟수
  - 급액EC(dS/m)
  - 급액pH
  - 급액량(회당)
  - 재배형태
epochs:
  desc: null
  value: 3000
hiddensize:
  desc: null
  value: 128
interpolation:
  desc: null
  value:
  - 지온
  - 지습
preprocess_target:
  desc: null
  value:
  - 내부CO2
  - 내부습도
  - 내부온도
